//! Command-line argument parsing for the binary.
//!
//! The binary supports three behaviours:
//! - **Help mode** (no arguments): prints usage to stderr and exits 0.
//! - **GUI mode** (`--gui`): opens the egui desktop window.
//! - **Headless mode** (`--headless`, or `--stdio` alone): no window; the bot
//!   auto-connects and the process exits when the MCP transport closes or on
//!   shutdown.
//!
//! Parsing is clap-derive based ([clap::Parser]); the flag set and the
//! precedence rules are unchanged from the previous hand-rolled parser:
//! `--headless` wins over `--gui`, `--stdio` alone implies headless, a
//! `--headless` wins over `--gui`, `--stdio` alone implies headless,
//! idempotent. `-V`/`--version` was added by clap (prints
//! `CARGO_PKG_VERSION`).
//!
//! **Never print to stdout from this module** — stdout is the MCP JSON-RPC
//! transport. Help/version text goes to stderr: [print_help] renders clap's
//! help to stderr, and `main` prints clap's `DisplayHelp` /
//! `DisplayVersion` errors to stderr before exiting 0.

use clap::{FromArgMatches, Parser};

/// Parsed command-line arguments (clap derive).
///
/// See [crate::cli] for the run-mode precedence rules applied on top of the
/// raw flags by [resolve_mode].
#[derive(Debug, Clone, PartialEq, Eq, Default, Parser)]
#[command(
    name = "minecraft-mcp-rs",
    about = "MCP server that controls a Minecraft bot",
    version,
    // The legacy hand-rolled parser treated repeated flags as idempotent
    // (last occurrence wins); keep that behaviour under clap.
    args_override_self = true
)]
pub struct CliArgs {
    /// Run without the egui window: auto-connect the bot on startup and exit
    /// when the MCP transport closes.
    #[arg(long)]
    pub headless: bool,
    /// Force the MCP stdio transport regardless of the configured transport
    /// (e.g. when launched by an MCP client as a server).
    #[arg(long = "stdio")]
    pub force_stdio: bool,
    /// Open the egui desktop window explicitly.
    #[arg(long)]
    pub gui: bool,
}

impl CliArgs {
    /// Whether no mode/flag was specified at all (all flags false). An
    /// empty argument set means the user asked for nothing, which
    /// [resolve_mode] treats as a help request.
    pub fn is_empty(&self) -> bool {
        !self.headless && !self.force_stdio && !self.gui
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunMode {
    /// Print help to stderr and exit 0 (no arguments, or `--help`).
    Help,
    /// Open the egui desktop window (`--gui`).
    Gui,
    /// Run without a window (`--headless`, or `--stdio` alone).
    Headless,
}

/// Resolve the run mode from the parsed arguments.
///
/// Precedence: help wins over everything; otherwise an explicit `--headless`
/// (or `--stdio` *without* `--gui`) forces headless; anything else runs the
pub fn resolve_mode(args: &CliArgs) -> RunMode {
    if args.is_empty() {
        RunMode::Help
    } else if args.headless || (args.force_stdio && !args.gui) {
        RunMode::Headless
    } else {
        RunMode::Gui
    }
}

/// Resolve the clap colour mode: cargo-style ALWAYS on, unless the standard
/// `NO_COLOR` environment variable is set (e.g. when piping logs to a file).
fn color_choice() -> clap::ColorChoice {
    if std::env::var_os("NO_COLOR").is_some() {
        clap::ColorChoice::Never
    } else {
        clap::ColorChoice::Always
    }
}

/// Parse the process arguments via clap.
///
/// `-h`/`--help` and `-V`/`--version` are handled by clap and surface
/// as [clap::error::ErrorKind::DisplayHelp] /
/// [clap::error::ErrorKind::DisplayVersion] errors — the caller prints them to
/// stderr and exits 0. Usage errors (unknown flag, missing value) surface as
/// clap errors; the caller prints them to stderr and exits 2.
///
/// Help/version/usage output is coloured cargo-style ([color_choice]) so an
/// unknown flag renders red even when stderr is piped (the previous
/// auto-detection silenced colours under `bunx`).
pub fn parse_cli_args() -> Result<CliArgs, clap::Error> {
    use clap::CommandFactory;
    let matches = CliArgs::command()
        .color(color_choice())
        .try_get_matches_from(std::env::args_os())?;
    CliArgs::from_arg_matches(&matches)
}

/// Print usage information to stderr (never stdout — stdout is the MCP
/// transport). The text is generated by clap from the [CliArgs] doc comments.
///
/// `StyledStr`'s plain `Display` always strips colour, so the ANSI view is
/// used when [color_choice] says colours are on (the `color` feature must
/// stay enabled in Cargo.toml).
pub fn print_help() {
    use clap::CommandFactory;
    let mut cmd = CliArgs::command().color(color_choice());
    match cmd.get_color() {
        clap::ColorChoice::Never => eprint!("{}", cmd.render_help()),
        _ => eprint!("{}", cmd.render_help().ansi()),
    }
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use clap::error::ErrorKind;

    use super::*;

    fn parse(args: &[&str]) -> Result<CliArgs, clap::Error> {
        let mut argv = vec!["minecraft-mcp-rs"];
        argv.extend_from_slice(args);
        CliArgs::try_parse_from(argv)
    }

    /// No arguments → defaults (all flags false).
    #[test]
    fn test_empty_args_returns_defaults() {
        assert_eq!(parse(&[]).unwrap(), CliArgs::default());
    }

    /// `--headless` alone enables headless mode.
    #[test]
    fn test_headless_flag() {
        let args = parse(&["--headless"]).unwrap();
        assert!(args.headless);
        assert!(!args.force_stdio);
        assert!(!args.gui);
    }

    /// `--stdio` alone forces the stdio transport.
    #[test]
    fn test_stdio_flag() {
        let args = parse(&["--stdio"]).unwrap();
        assert!(args.force_stdio);
        assert!(!args.headless);
    }

    /// `-h` and `--help` surface as clap DisplayHelp errors.
    #[test]
    fn test_help_flags() {
        assert!(matches!(
            parse(&["-h"]).unwrap_err().kind(),
            ErrorKind::DisplayHelp
        ));
        assert!(matches!(
            parse(&["--help"]).unwrap_err().kind(),
            ErrorKind::DisplayHelp
        ));
    }

    /// `-V` and `--version` surface as clap DisplayVersion errors.
    #[test]
    fn test_version_flags() {
        assert!(matches!(
            parse(&["-V"]).unwrap_err().kind(),
            ErrorKind::DisplayVersion
        ));
        assert!(matches!(
            parse(&["--version"]).unwrap_err().kind(),
            ErrorKind::DisplayVersion
        ));
    }

    /// Unknown arguments produce a usage error.
    #[test]
    fn test_unknown_argument_errors() {
        assert!(parse(&["--bogus"]).is_err());
    }

    /// All flags combined parse together.
    #[test]
    fn test_all_flags_combined() {
        let args = parse(&["--headless", "--stdio"]).unwrap();
        assert!(args.headless);
        assert!(args.force_stdio);
    }

    /// Repeated flags are idempotent (clap SetTrue).
    #[test]
    fn test_repeated_flags() {
        let args = parse(&["--headless", "--headless", "--stdio"]).unwrap();
        assert!(args.headless);
        assert!(args.force_stdio);
    }

    /// `--gui` alone enables the GUI mode.
    #[test]
    fn test_gui_flag() {
        let args = parse(&["--gui"]).unwrap();
        assert!(args.gui);
        assert!(!args.headless);
        assert!(!args.force_stdio);
    }

    /// No arguments → help mode (no longer starts the UI).
    #[test]
    fn test_resolve_mode_no_args_help() {
        assert_eq!(resolve_mode(&CliArgs::default()), RunMode::Help);
    }

    /// `--stdio` alone runs a headless stdio server.
    #[test]
    fn test_resolve_mode_stdio_alone_headless() {
        let args = parse(&["--stdio"]).unwrap();
        assert_eq!(resolve_mode(&args), RunMode::Headless);
    }

    /// `--gui` + `--stdio` → GUI (stdio alone is headless, but an explicit
    /// `--gui` overrides that implication).
    #[test]
    fn test_resolve_mode_gui_stdio() {
        let args = parse(&["--gui", "--stdio"]).unwrap();
        assert_eq!(resolve_mode(&args), RunMode::Gui);
    }

    /// `--headless` beats `--gui`.
    #[test]
    fn test_resolve_mode_headless_beats_gui() {
        let args = parse(&["--gui", "--headless"]).unwrap();
        assert_eq!(resolve_mode(&args), RunMode::Headless);
    }

    /// cargo-style help colouring: `render_help` under [`color_choice`]
    /// (NO_COLOR unset) must emit ANSI escape sequences — clap needs the
    /// `color` feature, which `features = ["derive"]` alone would silently
    /// drop, and the ANSI view, which the plain `Display` strips.
    #[test]
    fn test_help_renders_with_ansi_colours() {
        use clap::CommandFactory;
        let mut cmd = CliArgs::command().color(color_choice());
        let ansi_help = cmd.render_help().ansi().to_string();
        assert!(
            ansi_help.contains("\u{1b}["),
            "help must contain ANSI codes under the default colour mode, got: {ansi_help:?}"
        );
        let plain_help = cmd.render_help().to_string();
        assert!(
            !plain_help.contains("\u{1b}["),
            "plain Display must strip colours (fallback path), got: {plain_help:?}"
        );
    }

    /// `is_empty`: no flags → true; any single flag → false.
    #[test]
    fn test_is_empty() {
        assert!(CliArgs::default().is_empty());
        assert!(!parse(&["--headless"]).unwrap().is_empty());
        assert!(!parse(&["--stdio"]).unwrap().is_empty());
        assert!(!parse(&["--gui"]).unwrap().is_empty());
    }
}
